name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch: {}

jobs:
  docker:
    name: Build (matrix) and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            suffix: amd64
          - platform: linux/arm64
            suffix: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/aaacoder-ds/timeblocker:latest-${{ matrix.suffix }}
            ghcr.io/aaacoder-ds/timeblocker:${{ github.sha }}-${{ matrix.suffix }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('ghcr.io/aaacoder-ds/timeblocker:{0}-{1}', github.ref_name, matrix.suffix) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  manifest:
    name: Create multi-arch manifest tags
    needs: [docker]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest for :latest
        run: |
          docker buildx imagetools create \
            -t ghcr.io/aaacoder-ds/timeblocker:latest \
            ghcr.io/aaacoder-ds/timeblocker:latest-amd64 \
            ghcr.io/aaacoder-ds/timeblocker:latest-arm64

      - name: Create manifest for commit SHA
        run: |
          docker buildx imagetools create \
            -t ghcr.io/aaacoder-ds/timeblocker:${{ github.sha }} \
            ghcr.io/aaacoder-ds/timeblocker:${{ github.sha }}-amd64 \
            ghcr.io/aaacoder-ds/timeblocker:${{ github.sha }}-arm64

      - name: Create manifest for tag ref
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker buildx imagetools create \
            -t ghcr.io/aaacoder-ds/timeblocker:${{ github.ref_name }} \
            ghcr.io/aaacoder-ds/timeblocker:${{ github.ref_name }}-amd64 \
            ghcr.io/aaacoder-ds/timeblocker:${{ github.ref_name }}-arm64

